name: lint
on: [push, pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: pnpm install
        run: pnpm install
      - name: pnpm run build
        run: pnpm run build
      - name: pnpm run lint
        run: pnpm run lint
      - name: pnpm run tsd
        run: pnpm run tsd
